BASELINE1_Y = 132
BASELINE2_Y = 165
MIDDLE_LINE_Y = 140
HOLE_XY = (290, MIDDLE_LINE_Y)
PAR_XY = (310, BASELINE1_Y)
PAR_DISTANCE_XY = (310, BASELINE2_Y)
NAME_XY = (670, MIDDLE_LINE_Y)

CURR_SCORE_XY = (1018, MIDDLE_LINE_Y)
CURR_SHOT_XY = (1084, BASELINE1_Y)
SHOT_XY = (1084, BASELINE2_Y)
TO_HOLE_XY = (1306, BASELINE1_Y)
CLUB_XY = (1306, BASELINE2_Y)

# Fonts
HANSIEF_FONT = 'Hansief.otf'
DANCE_FONT = 'Dance.ttf'
MONTSERRAT_LIGHT = 'Montserrat-Light.ttf'
MONTSERRAT_BOLD = 'Montserrat-Bold.ttf'

# Font Sizes
HOLE_FONT_SIZE = 45
TWO_LINE_FONT_SIZE = 30

# Images
SCORE_TOP_BG = 'images/latest_score_bg_small.png'

# Colors
DARK_FONT = '#0b0b69'
WHITE_FONT = (255, 255, 255)

PLAYER_NAME = 'GLENN ESPINA'
